<?php

namespace League\Skeleton;

use Mockery;

class TestCase extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Silly\Edition\Pimple\Application
     */
    protected $app;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createApplication();
    }


    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $this->app = $app;
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        Mockery::close();
    }
}